#!/bin/bash


function title {
	echo -n $1"@"$2"> "

}



function connectLogin {

# $1: userName $2:machine to connect $3: password
	flag1=false
	flag2=false
	flag3=false

	while read userName userLevel password
	do
		if [[ $userName == $1 ]] && [[ $password == $3 ]]
		then
			flag1=true
			echo 'Password right, search $2'

			while read machine levelMachine
			do

				if [ $machine == $2 ]
				then

					flag2=true
					echo 'Try to connect to $machine'
					
					if [ $userLevel -lt $levelMachine ] || [ $userLevel == $levelMachine ]
					then

						flag3=true
						break

					else
						echo "$userName haven't suffient right for $machine"
						exit
					fi

				fi

			done < machines
		fi

		if [[ $flag3 == true ]]
		then
			#statements
			break
		fi

	done < users

	if [ $flag1 == true ] && [ $flag2 == true ] && [ $flag3 == true ]
	then
		echo 'Connexion successful'
		echo 'We already connect $1 to $2'
		sleep 2
		clear
		./connect $1 $2

	
	elif [ $flag1 == false ]
	then

		#statements
		echo "User or password not correct!"
		exit

	elif [ $flag2 == false ]
	then

		#statements
		echo "We can't find $2"
		exit

	fi
}






function who {

	echo 'who'
}


function rusers {

	echo 'who'
}

function rhost {

	echo 'who'
}

function connect {

	echo 'who'
}

function su {
	if [[ $# -eq 2 ]]
	then

			#statements
			echo "Mode Connect: connet to $2"
			echo "Password of $3:"
			read -s password
			echo 'Wait...'
			connectLogin $2 $1 $password
			break
	fi
}

function passwd {

	echo 'who'
}

function write {

	echo 'who'
}

# Main

echo 'Mode users'
title $1 $2
while read input

do

	if [[ "$input" != "exit" ]]; then

	   case "$input" in

		"who")

		  who

		;;

		"rusers")

		  rusers

		;;

		"rhost")

		  rhost

		;;

		"connect")

		  connect

		;;

		"su")

		  su

		;;

		"passwd")

		  passwd

		;;

		"finger")

		  finger

		;;

		"write "*"@"*" "*)

		  write $input

		;;

		"clear")

		  clear

		;;

		*)

		  echo ""

		  echo $input": command not found"

		  echo ""		  
		;;

	   esac

	else
		break

	fi
	title $1 $2

done
echo ""
echo "Exit System"
echo ""